SAMPLE_RATE = 16000 # 16000
HOP_LENGTH =  384 # SAMPLE_RATE * 32 // 1000
ONSET_LENGTH = SAMPLE_RATE * 32 // 1000
OFFSET_LENGTH = SAMPLE_RATE * 32 // 1000
HOPS_IN_ONSET = ONSET_LENGTH // HOP_LENGTH
HOPS_IN_OFFSET = OFFSET_LENGTH // HOP_LENGTH
MIN_MIDI = 40
MAX_MIDI = 88

N_BINS = 229 # Default using Mel spectrograms
MEL_FMIN = 82 # 30
MEL_FMAX = 5000 # SAMPLE_RATE // 2

# New parameter for Guqin
# N_BINS = 400 # Default using Mel spectrograms
# MEL_FMIN = 20
# MEL_FMAX = SAMPLE_RATE // 2


WINDOW_LENGTH = 2048 # Window of audio sequence
WINDOW_SIZE = 9      # Window of frame of feature 

#DEFAULT_DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

TOTAL_LABEL_FILES = 16
TOTAL_UNLABEL_FILES = 33
TOTAL_VALID_FILES = 2
TOTAL_TEST_FILES = 1